In [19]:
print("hello world")

hello world

In [20]:
import pandas as pd

df1 = pd.read_csv("./data/track6_reports_dataset.csv")

df1.head()

,source_file,report_id,entity_reference,submission_date,currency_code,narrative,narrative_length,report_type,transaction_number,amount_local,...,transaction_mode_code,transaction_mode,from_institution,from_account_name,from_account_number,from_country,to_institution,to_account_name,to_account_number,to_country
0,report_000001.xml,RPT-2026-000001,NIMB-2026-000001,2026-06-14T15:42:08,NPR,Suspicious transaction observed.,32,Type-A,SAMLD-7401327478-317,535368.64,...,Z,Cash Deposit transfer,PCBL,John Jensen,NP00000000003412850188,GB,SBL,Jeremy Martinez,NP00000000003980427782,GB
1,report_000002.xml,RPT-2026-000002,SBL-2026-000002,2026-06-14T15:42:08,NPR,During the branch's periodic transaction-monit...,1264,Type-B,SAMLD-6340007440-1206,21807.13,...,A,Cash Withdrawal transfer,ADBL,Sally Dominguez,NP00000000000983174071,GB,HBL,Henry King,NP00000000000894070684,IN
2,report_000003.xml,RPT-2026-000003,RBBL-2026-000003,2026-06-14T15:42:08,NPR,During the branch's periodic transaction-monit...,1283,Type-B,SAMLD-3758118046-1649,1214019.81,...,F,Cross-border transfer,KUMARI,"Cook, Flores and Ray",NP00000000002968635055,GB,SBL,Chad Mccarty,NP00000000000310823462,MX
3,report_000004.xml,RPT-2026-000004,HBL-2026-000004,2026-06-14T15:42:08,NPR,During the branch's periodic transaction-monit...,1264,Type-B,SAMLD-445154846-1954,813935.97,...,F,Cross-border transfer,PRABHU,Robert King,NP00000000001187666276,GB,LAXMI,Sarah English,NP00000000004011650754,NG
4,report_000005.xml,RPT-2026-000005,MBL-2026-000005,2026-06-14T15:42:08,NPR,Suspicious transaction observed.,32,Type-A,SAMLD-2758469152-3304,1610735.12,...,Z,Debit card transfer,MEGA,Porter LLC,NP00000000003628175933,GB,MEGA,Terrence Davis,NP00000000003038338293,GB

In [21]:
import pandas as pd

df = pd.read_csv("./data/track6_reports_with_entities.csv")

df.head()

,source_file,report_id,entity_reference,submission_date,currency_code,narrative,narrative_length,report_type,transaction_number,amount_local,...,to_account_number,to_country,entities_json,entities_customer_names,entities_counterparty_names,entities_bank_names,entities_amounts,entities_dates,entities_transaction_modes,entities_countries
0,report_000001.xml,RPT-2026-000001,NIMB-2026-000001,2026-06-14T15:42:08,NPR,Suspicious transaction observed.,32,Type-A,SAMLD-7401327478-317,535368.64,...,NP00000000003980427782,GB,"{""account_numbers"": [""NP00000000003412850188"",...",John Jensen,Jeremy Martinez,PCBL; SBL,NPR 535368.64,2022-10-07,Cash Deposit transfer,GB
1,report_000002.xml,RPT-2026-000002,SBL-2026-000002,2026-06-14T15:42:08,NPR,During the branch's periodic transaction-monit...,1264,Type-B,SAMLD-6340007440-1206,21807.13,...,NP00000000000894070684,IN,"{""account_numbers"": [""NP00000000000983174071"",...",Sally Dominguez,Henry King,ADBL; HBL,NPR 21807.13,2022-10-07,Cash Withdrawal transfer,GB; IN
2,report_000003.xml,RPT-2026-000003,RBBL-2026-000003,2026-06-14T15:42:08,NPR,During the branch's periodic transaction-monit...,1283,Type-B,SAMLD-3758118046-1649,1214019.81,...,NP00000000000310823462,MX,"{""account_numbers"": [""NP00000000002968635055"",...","Cook, Flores and Ray",Chad Mccarty,KUMARI; SBL,NPR 1214019.81,2022-10-07,Cross-border transfer,GB; MX
3,report_000004.xml,RPT-2026-000004,HBL-2026-000004,2026-06-14T15:42:08,NPR,During the branch's periodic transaction-monit...,1264,Type-B,SAMLD-445154846-1954,813935.97,...,NP00000000004011650754,NG,"{""account_numbers"": [""NP00000000001187666276"",...",Robert King,Sarah English,PRABHU; LAXMI,NPR 813935.97,2022-10-07,Cross-border transfer,GB; NG
4,report_000005.xml,RPT-2026-000005,MBL-2026-000005,2026-06-14T15:42:08,NPR,Suspicious transaction observed.,32,Type-A,SAMLD-2758469152-3304,1610735.12,...,NP00000000003038338293,GB,"{""account_numbers"": [""NP00000000003628175933"",...",Porter LLC,Terrence Davis,MEGA,NPR 1610735.12,2022-10-07,Debit card transfer,GB

In [24]:
df.shape

(276, 30)

In [25]:
df.columns

Index(['source_file', 'report_id', 'entity_reference', 'submission_date',
       'currency_code', 'narrative', 'narrative_length', 'report_type',
       'transaction_number', 'amount_local', 'date_transaction',
       'transaction_location', 'transaction_mode_code', 'transaction_mode',
       'from_institution', 'from_account_name', 'from_account_number',
       'from_country', 'to_institution', 'to_account_name',
       'to_account_number', 'to_country', 'entities_json',
       'entities_customer_names', 'entities_counterparty_names',
       'entities_bank_names', 'entities_amounts', 'entities_dates',
       'entities_transaction_modes', 'entities_countries'],
      dtype='str')

In [27]:
df["report_type"].value_counts()

report_type
Type-B    176
Type-A    100
Name: count, dtype: int64

In [28]:
df["currency_code"].value_counts()

currency_code
NPR    276
Name: count, dtype: int64

In [29]:
df["transaction_mode"].value_counts()

transaction_mode
Cross-border transfer       66
Cheque transfer             64
ACH transfer                51
Cash Deposit transfer       47
Cash Withdrawal transfer    18
Debit card transfer         15
Credit card transfer        15
Name: count, dtype: int64

In [30]:
df["narrative_length"].describe()

count     276.000000
mean      807.286232
std       585.588942
min        32.000000
25%        32.000000
50%      1236.000000
75%      1245.000000
max      1291.000000
Name: narrative_length, dtype: float64

In [31]:
df["narrative_length"].hist(bins=30)

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.